# [[language]]
# name = "mylang"
# scope = "source.mylang"
# injection-regex = "mylang"
# file-types = ["mylang", "myl"]
# comment-token = "#"
# indent = { tab-width = 2, unit = "  " }
# language-server = { command = "mylang-lsp", args = ["--stdio"], environment = { "ENV1" = "value1", "ENV2" = "value2" } }
# formatter = { command = "mylang-formatter" , args = ["--stdin"] }

[[language]]
name = "javascript"
scope = "source.js"
file-types = ["js", "jsx"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "typescript-language-server" ]
formatter = { command = "prettier_d_slim" , args = ["--write"] }

[[language]]
name = "typescript"
scope = "source.ts"
file-types = ["ts", "tsx"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-servers = [ "typescript-language-server" ]
formatter = { command = "prettier_d_slim" , args = ["--write"] }

[[language]]
name = "json"
file-types = ["json"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-servers = [ "vscode-json-language-server" ]
formatter = { command = "prettier_d_slim" , args = ["--write"] }

[[language]]
name = "rust"
auto-format = true

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c", "h"] # TODO: ["h"]
roots = []
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 2, unit = "  " }
